project_id = "vqebihhxkiitvyoqnivq"

[functions.update-company-status]
verify_jwt = false

[functions.validate-coupon]
verify_jwt = false

[functions.update-user-password]
verify_jwt = false

[functions.create-admin]
verify_jwt = false

[functions.delete-coupon]
verify_jwt = false
